version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile   # Asegúrate de tener un Dockerfile para tu aplicación Nest.js
    depends_on:
      - mongodb
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://localhost:27018/your-database   # Actualiza el nombre de la base de datos según tus necesidades

volumes:
  mongodb-data:
